"""LawSearch MVP UI: scenario -> ranked cases -> FILAC briefs with verify links.

Talks to the FastAPI backend over HTTP so the embedding model lives in one process.

    streamlit run ui/streamlit_app.py      (with `uvicorn app.main:app` running)
"""

import os

import httpx
import streamlit as st

API = os.environ.get("LAWSEARCH_API", "http://localhost:8000")
SECTION_LABELS = {
    "facts": "Facts", "issues": "Issues", "law": "Law", "analysis": "Analysis", "conclusion": "Conclusion",
}
ATTRIBUTION_LABELS = {
    "concurrence": "Concurrence", "dissent": "Dissent", "party_argument": "Party argument", "lower_court": "Lower court",
}
RELIED_ON_LABELS = {
    "court": "court", "party": "a party", "lower_court": "lower court", "concurrence": "concurrence", "dissent": "dissent",
}

st.set_page_config(page_title="LawSearch", page_icon="⚖️", layout="wide")


@st.cache_data(ttl=3600)
def load_courts() -> list[dict]:
    return httpx.get(f"{API}/courts", timeout=30).json()


def fetch_cached_brief(case_id: str) -> dict | None:
    response = httpx.get(f"{API}/cases/{case_id}/filac", timeout=30)
    return response.json() if response.status_code == 200 else None


def anchor_label(anchor: int, anchor_type: str) -> str:
    return f"¶{anchor}" if anchor_type == "paragraph" else f"passage {anchor}"


def render_brief(brief: dict) -> None:
    summary, verification = brief["summary"], brief["verification"]
    anchor_type = verification["anchor_type"]

    if verification["problems"]:
        st.warning(
            f"{verification['problems']} item(s) could not be verified against the decision text "
            "(marked ⚠). Check them before relying on this brief."
        )

    for section, label in SECTION_LABELS.items():
        block = summary[section]
        st.markdown(f"**{label}**")
        if block["status"] == "not_stated_in_text" or not block["items"]:
            st.caption("Not stated in the decision text.")
            continue
        lines = []
        for item, check in zip(block["items"], verification["sections"][section]):
            where = anchor_label(item["anchor"], anchor_type)
            flag = "" if check["anchor_ok"] else " ⚠ *anchor not in decision*"
            if section == "law":
                if not check["found_in_document"]:
                    flag += " ⚠ *not found in text*"
                in_corpus = " · in corpus" if check.get("resolved_case") else ""
                statutes = ""
                for resolved in check.get("resolved_sections", []):
                    link = f"[{resolved['title']} s. {resolved['section']}]({resolved['url']})"
                    note = ""
                    if resolved["in_force_after_decision"]:
                        note = f" ⚠ *current wording in force since {resolved['in_force_start']}, after this decision*"
                    statutes += f"\n  - → {link}{note}"
                lines.append(
                    f"- {item['authority']} — {item['kind']}, relied on by "
                    f"{RELIED_ON_LABELS[item['relied_on_by']]} `{where}`{in_corpus}{flag}{statutes}"
                )
            elif section == "analysis" and item["attribution"] != "court":
                lines.append(f"- *{ATTRIBUTION_LABELS[item['attribution']]}:* {item['text']} `{where}`{flag}")
            else:
                lines.append(f"- {item['text']} `{where}`{flag}")
        st.markdown("\n".join(lines))

    with st.expander(f"Cited {anchor_type}s (unofficial text)"):
        for anchor, text in verification["anchor_text"].items():
            st.markdown(f"**{anchor_label(int(anchor), anchor_type)}**")
            st.text(text)

    usage = brief["usage"]
    st.caption(
        f"AI-generated by {usage.get('served_by', brief['model'])} via {brief['backend']} · "
        f"prompt {brief['prompt_version']} · {brief['created_at'][:10]}"
    )


JURISDICTION_LABELS = {
    "federal": "Federal", "ontario": "Ontario", "other_province": "Other province", "unknown": "Unknown",
}


def render_fingerprint(fp: dict) -> None:
    with st.expander("What we understood from your scenario", expanded=False):
        st.markdown(f"**Jurisdiction:** {JURISDICTION_LABELS.get(fp['jurisdiction'], fp['jurisdiction'])}")
        for label, key in [
            ("Areas of law", "areas_of_law"), ("Issues", "issues"), ("Key facts", "key_facts"),
            ("Causes of action", "causes_of_action"), ("Candidate statutes", "candidate_statutes"),
            ("Search terms", "search_terms"),
        ]:
            if fp[key]:
                st.markdown(f"**{label}:** " + "; ".join(fp[key]))
        st.caption(f"Fingerprinted by {fp.get('model', fp['backend'])} via {fp['backend']}")


def section_heading(section: dict) -> str:
    note = f" — {section['marginal_note']}" if section["marginal_note"] else ""
    return f"{section['title']}, s. {section['section_label']}{note}"


def render_sections(sections: list[dict]) -> None:
    st.subheader("Relevant legislation")
    st.caption(
        "Federal legislation from Justice Laws; Ontario Acts from A2AJ (Ontario regulations aren't "
        "covered yet). Unofficial text — check each section's \"current to\" date and the official version."
    )
    cited_by_section = st.session_state.setdefault("section_citations", {})
    for section in sections:
        with st.container(border=True):
            st.markdown(f"**{section_heading(section)}**")
            facts = [section["citation"] or section["code"]]
            if section["consolidation_date"]:
                facts.append(f"current to {section['consolidation_date']}")
            if section["in_force_start"]:
                facts.append(f"in force since {section['in_force_start']}")
            facts.append(f"cited in {section['cited_by_count']:,} decisions")
            if section["citing_cases"]:
                facts.append(f"cited by {section['citing_cases']} of the top cases")
            if section["url"]:
                facts.append(f"[Official text]({section['url']})")
            st.caption(" · ".join(facts))
            with st.expander("Text"):
                st.text(section["text"].split("\n", 1)[-1])
            chunk_id = section["chunk_id"]
            if chunk_id in cited_by_section:
                with st.expander("Decisions citing this section", expanded=True):
                    for c in cited_by_section[chunk_id]:
                        st.markdown(f"- {c['citation']} · {c['court']} · {c['style_of_cause']}")
            elif section["cited_by_count"] and st.button("Decisions citing this section", key=f"citing-{chunk_id}"):
                cited_by_section[chunk_id] = httpx.get(f"{API}/sections/{chunk_id}", timeout=30).json()["citing_cases"]
                st.rerun()


def render_case_statutes(case_id: str) -> None:
    statutes = st.session_state.setdefault("case_statutes", {})
    if case_id in statutes:
        with st.expander(f"Legislation cited in this decision ({len(statutes[case_id])})", expanded=True):
            if not statutes[case_id]:
                st.caption("No federal or Ontario statute sections recognized.")
            for section in statutes[case_id]:
                link = f" · [Official text]({section['url']})" if section["url"] else ""
                st.markdown(f"- {section_heading(section)}{link}")
    elif st.button("Legislation cited", key=f"statutes-{case_id}"):
        statutes[case_id] = httpx.get(f"{API}/cases/{case_id}/statutes", timeout=30).json()
        st.rerun()


def render_case(rank: int, case: dict) -> None:
    case_id = case["case_id"]
    briefs = st.session_state.setdefault("briefs", {})
    if case_id not in briefs:
        briefs[case_id] = fetch_cached_brief(case_id)

    with st.container(border=True):
        date = case["decision_date"] or "date unknown"
        st.markdown(f"#### {rank}. {case['style_of_cause']}")
        links = f"[Official text]({case['url']})" if case["url"] else "No official link"
        signals = [f"cited by {case['cited_by_count']:,} decisions in the corpus"]
        if case["citing_seeds"]:
            signals.append(f"cited by {case['citing_seeds']} of the top matches")
        st.caption(f"{case['citation']} · {case['court']} · {date} · {links} · {' · '.join(signals)}")

        with st.expander("Matching passages"):
            for passage in case["passages"]:
                if passage["para_no"] is None:
                    where = "unnumbered passage"
                elif passage["para_no"] == passage["para_end"]:
                    where = f"¶{passage['para_no']}"
                else:
                    where = f"¶{passage['para_no']}–{passage['para_end']}"
                how = " + ".join("found via citations" if m == "graph" else m for m in passage["matched_by"])
                st.markdown(f"**{where}** · {how}")
                st.text(passage["text"])

        render_case_statutes(case_id)

        brief = briefs[case_id]
        if brief:
            with st.expander("FILAC brief", expanded=True):
                render_brief(brief)
        elif st.button("Generate FILAC brief", key=f"generate-{case_id}"):
            with st.spinner("Reading the decision — long judgments can take a few minutes..."):
                response = httpx.post(f"{API}/cases/{case_id}/filac", timeout=1200)
            if response.status_code == 200:
                briefs[case_id] = response.json()
                st.rerun()
            else:
                st.error(response.json().get("detail", f"Brief failed (HTTP {response.status_code})"))


CANLII_NOTICES = {
    "partial": "CanLII stopped answering part-way, so some decisions below may lack details.",
    "no_seeds": "None of the top cases could be looked up on CanLII, so there was nothing to trace.",
    "disabled": "CanLII detection is off (no API key configured).",
    "budget_exhausted": "Today's CanLII query budget is used up; try again tomorrow.",
    "error": "CanLII lookup failed.",
}


def render_canlii(query: str, results: list[dict]) -> None:
    st.subheader("Ontario Superior Court and tribunal decisions (CanLII)")
    st.caption(
        "These decisions aren't in LawSearch's corpus. They were found on CanLII because they cite "
        "the top cases above, then ranked by CanLII's own keywords for each decision. Link-out only: "
        "no text or FILAC brief here, and relevance is a lead to check, not a finding."
    )
    if st.session_state.get("canlii") is None:
        with st.spinner("Tracing citations on CanLII (up to ~20 s when nothing is cached)..."):
            try:
                response = httpx.post(
                    f"{API}/canlii/candidates",
                    json={"query": query, "seed_case_ids": [c["case_id"] for c in results], "k": 8},
                    timeout=300,
                )
                body = response.json() if response.status_code == 200 else {
                    "status": "error", "message": f"HTTP {response.status_code}", "candidates": [],
                }
            except httpx.HTTPError as exc:
                body = {"status": "error", "message": type(exc).__name__, "candidates": []}
        st.session_state.canlii = body
    body = st.session_state.canlii

    if body["status"] != "ok":
        notice = CANLII_NOTICES.get(body["status"], "CanLII lookup failed.")
        detail = f" ({body['message']})" if body.get("message") and body["status"] in ("error", "partial") else ""
        st.info(notice + detail)
    if not body["candidates"]:
        if body["status"] in ("ok", "partial"):
            st.caption("No sufficiently related Ontario decisions cite the top cases.")
        return
    for cand in body["candidates"]:
        with st.container(border=True):
            title = cand["title"] or cand["citation"] or "Untitled decision"
            st.markdown(f"**[{title}]({cand['url']})**" if cand["url"] else f"**{title}**")
            facts = [f for f in (cand["citation"], cand["court_name"], cand["decision_date"]) if f]
            cites = "; ".join(s["title"] or s["citation"] for s in cand["cites"])
            st.caption(" · ".join(facts) + f" · cites {cites}")
            if cand["topics"]:
                st.caption(f"Topics: {cand['topics']}")
            if cand["keywords"]:
                with st.expander("CanLII keywords"):
                    st.write(cand["keywords"])
    if body.get("queries_sent"):
        st.caption(f"Used {body['queries_sent']} CanLII queries ({body['queries_today']:,}/{body['daily_limit']:,} today).")


st.title("LawSearch")
st.caption(
    "Research assistance, not legal advice. Case text comes from unofficial copies and briefs are "
    "AI-generated — always verify against the official decision."
)

with st.sidebar:
    st.header("Filters")
    try:
        courts = load_courts()
    except httpx.HTTPError:
        st.error(f"Cannot reach the LawSearch API at {API}. Start it with `uvicorn app.main:app`.")
        st.stop()
    court_names = {c["court"]: f"{c['court']} ({c['cases']:,})" for c in courts}
    selected_courts = st.multiselect("Courts and tribunals", list(court_names), format_func=court_names.get)
    k = st.slider("Cases to show", 3, 30, 10)
    st.divider()
    st.caption(
        "Coverage: federal courts and tribunals from A2AJ (Federal Court and FCA decisions start "
        "in 2001), plus ONCA (from 1998). Ontario Superior Court and tribunal decisions aren't in "
        "the corpus; for Ontario scenarios, ones that cite the top cases are listed as CanLII links."
    )

scenario = st.text_area(
    "Describe the situation",
    height=150,
    placeholder="e.g. My client was dismissed without cause and her bonus plan says she must be actively employed to receive it...",
)
uploaded_file = st.file_uploader("...or upload a scenario document", type=["pdf", "docx", "txt", "md"])
st.caption(
    "Either field works on its own; if both are filled the uploaded file is used. "
    "Courts/date filters above apply once results come back — the fingerprint step decides "
    "whether to search at all (e.g. other provinces aren't covered yet)."
)

if st.button("Search", type="primary", disabled=not (scenario.strip() or uploaded_file)):
    with st.spinner("Reading the scenario and searching..."):
        data = {"k": k, "courts": selected_courts or []}
        if uploaded_file is not None:
            files = {"file": (uploaded_file.name, uploaded_file.getvalue())}
        else:
            files = None
            data["text"] = scenario
        response = httpx.post(f"{API}/scenarios", data=data, files=files, timeout=180)
    if response.status_code == 200:
        body = response.json()
        st.session_state.fingerprint = body["fingerprint"]
        st.session_state.gate = body["gate"]
        st.session_state.canlii = None
        if body["results"]:
            st.session_state.results = body["results"]["results"]
            st.session_state.sections = body["results"]["sections"]
            st.session_state.search_query = body["results"]["query"]
        else:
            st.session_state.results, st.session_state.sections = None, None
    else:
        st.session_state.fingerprint, st.session_state.gate = None, None
        st.session_state.results, st.session_state.sections = None, None
        detail = response.json().get("detail", response.text[:300]) if response.headers.get(
            "content-type", ""
        ).startswith("application/json") else response.text[:300]
        st.error(f"Search failed: {detail}")

fingerprint = st.session_state.get("fingerprint")
if fingerprint:
    render_fingerprint(fingerprint)

gate = st.session_state.get("gate")
if gate and gate["status"] == "unsupported_jurisdiction":
    st.warning(gate["message"])
elif gate and gate["status"] == "needs_clarification":
    st.info(f"Before searching, it would help to know: {gate['message']}")

results = st.session_state.get("results")
if results is not None:
    if st.session_state.get("sections"):
        render_sections(st.session_state.sections)
    st.subheader("Cases")
    if not results:
        st.info("No matching cases.")
    for rank, case in enumerate(results, 1):
        render_case(rank, case)
    if results and fingerprint and fingerprint["jurisdiction"] == "ontario":
        render_canlii(st.session_state.search_query, results)
