"""LawSearch MVP UI: scenario -> ranked cases -> FILAC briefs with verify links.

Talks to the FastAPI backend over HTTP so the embedding model lives in one process.

    streamlit run ui/streamlit_app.py      (with `uvicorn app.main:app` running)
"""

import os

import httpx
import streamlit as st

API = os.environ.get("LAWSEARCH_API", "http://localhost:8000")
SECTION_LABELS = {
    "facts": "Facts", "issues": "Issues", "law": "Law", "analysis": "Analysis", "conclusion": "Conclusion",
}
ATTRIBUTION_LABELS = {
    "concurrence": "Concurrence", "dissent": "Dissent", "party_argument": "Party argument", "lower_court": "Lower court",
}
RELIED_ON_LABELS = {
    "court": "court", "party": "a party", "lower_court": "lower court", "concurrence": "concurrence", "dissent": "dissent",
}

st.set_page_config(page_title="LawSearch", page_icon="⚖️", layout="wide")


@st.cache_data(ttl=3600)
def load_courts() -> list[dict]:
    return httpx.get(f"{API}/courts", timeout=30).json()


def fetch_cached_brief(case_id: str) -> dict | None:
    response = httpx.get(f"{API}/cases/{case_id}/filac", timeout=30)
    return response.json() if response.status_code == 200 else None


def anchor_label(anchor: int, anchor_type: str) -> str:
    return f"¶{anchor}" if anchor_type == "paragraph" else f"passage {anchor}"


def render_brief(brief: dict) -> None:
    summary, verification = brief["summary"], brief["verification"]
    anchor_type = verification["anchor_type"]

    if verification["problems"]:
        st.warning(
            f"{verification['problems']} item(s) could not be verified against the decision text "
            "(marked ⚠). Check them before relying on this brief."
        )

    for section, label in SECTION_LABELS.items():
        block = summary[section]
        st.markdown(f"**{label}**")
        if block["status"] == "not_stated_in_text" or not block["items"]:
            st.caption("Not stated in the decision text.")
            continue
        lines = []
        for item, check in zip(block["items"], verification["sections"][section]):
            where = anchor_label(item["anchor"], anchor_type)
            flag = "" if check["anchor_ok"] else " ⚠ *anchor not in decision*"
            if section == "law":
                if not check["found_in_document"]:
                    flag += " ⚠ *not found in text*"
                in_corpus = " · in corpus" if check.get("resolved_case") else ""
                lines.append(
                    f"- {item['authority']} — {item['kind']}, relied on by "
                    f"{RELIED_ON_LABELS[item['relied_on_by']]} `{where}`{in_corpus}{flag}"
                )
            elif section == "analysis" and item["attribution"] != "court":
                lines.append(f"- *{ATTRIBUTION_LABELS[item['attribution']]}:* {item['text']} `{where}`{flag}")
            else:
                lines.append(f"- {item['text']} `{where}`{flag}")
        st.markdown("\n".join(lines))

    with st.expander(f"Cited {anchor_type}s (unofficial text)"):
        for anchor, text in verification["anchor_text"].items():
            st.markdown(f"**{anchor_label(int(anchor), anchor_type)}**")
            st.text(text)

    usage = brief["usage"]
    st.caption(
        f"AI-generated by {usage.get('served_by', brief['model'])} via {brief['backend']} · "
        f"prompt {brief['prompt_version']} · {brief['created_at'][:10]}"
    )


def render_case(rank: int, case: dict) -> None:
    case_id = case["case_id"]
    briefs = st.session_state.setdefault("briefs", {})
    if case_id not in briefs:
        briefs[case_id] = fetch_cached_brief(case_id)

    with st.container(border=True):
        date = case["decision_date"] or "date unknown"
        st.markdown(f"#### {rank}. {case['style_of_cause']}")
        links = f"[Official text]({case['url']})" if case["url"] else "No official link"
        signals = [f"cited by {case['cited_by_count']:,} decisions in the corpus"]
        if case["citing_seeds"]:
            signals.append(f"cited by {case['citing_seeds']} of the top matches")
        st.caption(f"{case['citation']} · {case['court']} · {date} · {links} · {' · '.join(signals)}")

        with st.expander("Matching passages"):
            for passage in case["passages"]:
                if passage["para_no"] is None:
                    where = "unnumbered passage"
                elif passage["para_no"] == passage["para_end"]:
                    where = f"¶{passage['para_no']}"
                else:
                    where = f"¶{passage['para_no']}–{passage['para_end']}"
                how = " + ".join("found via citations" if m == "graph" else m for m in passage["matched_by"])
                st.markdown(f"**{where}** · {how}")
                st.text(passage["text"])

        brief = briefs[case_id]
        if brief:
            with st.expander("FILAC brief", expanded=True):
                render_brief(brief)
        elif st.button("Generate FILAC brief", key=f"generate-{case_id}"):
            with st.spinner("Reading the decision — long judgments can take a few minutes..."):
                response = httpx.post(f"{API}/cases/{case_id}/filac", timeout=1200)
            if response.status_code == 200:
                briefs[case_id] = response.json()
                st.rerun()
            else:
                st.error(response.json().get("detail", f"Brief failed (HTTP {response.status_code})"))


st.title("LawSearch")
st.caption(
    "Research assistance, not legal advice. Case text comes from unofficial copies and briefs are "
    "AI-generated — always verify against the official decision."
)

with st.sidebar:
    st.header("Filters")
    try:
        courts = load_courts()
    except httpx.HTTPError:
        st.error(f"Cannot reach the LawSearch API at {API}. Start it with `uvicorn app.main:app`.")
        st.stop()
    court_names = {c["court"]: f"{c['court']} ({c['cases']:,})" for c in courts}
    selected_courts = st.multiselect("Courts and tribunals", list(court_names), format_func=court_names.get)
    k = st.slider("Cases to show", 3, 30, 10)
    st.divider()
    st.caption(
        "Coverage: federal courts and tribunals from A2AJ. Federal Court and FCA decisions start in 2001. "
        "Ontario courts are not covered yet."
    )

scenario = st.text_area(
    "Describe the situation",
    height=150,
    placeholder="e.g. My client was dismissed without cause and her bonus plan says she must be actively employed to receive it...",
)

if st.button("Search", type="primary", disabled=not scenario.strip()):
    with st.spinner("Searching..."):
        response = httpx.post(
            f"{API}/search",
            json={"query": scenario, "k": k, "courts": selected_courts or None},
            timeout=120,
        )
    if response.status_code == 200:
        st.session_state.results = response.json()["results"]
    else:
        st.session_state.results = []
        st.error(f"Search failed: {response.text[:300]}")

results = st.session_state.get("results")
if results is not None:
    if not results:
        st.info("No matching cases.")
    for rank, case in enumerate(results, 1):
        render_case(rank, case)
